kind: pipeline
type: docker
name: continuous-integration
# type property ?

trigger:
    event:
        - pull_request
# plutot trigger le file entier et preciser les steps impactées en fonction du context via un when

steps:
    - name: quality-checks
      image: node # versionning ?
      commands:
          - npm install
          - npm run lint
          - npm run format
          - npx tsc
          - npx prisma validate
          - npm run test
      environment:
          DATABASE_URL: postgresql://db:password@database:5432/db?schema=public
# eviter d'hardcoder les valeurs, utiliser des secrets ou ajouter le fichier au gitignore

# pas sur de l'interet d'un npm format, surtout vu le .prettierrc
# le lint devrait etre suffisament paramétré pour forcer les bonnes pratiques dev


services:
    - name: database
      image: postgres:9-alpine
      environment:
          POSTGRES_USER: db
          POSTGRES_DB: password
# ne pas afficher les credentials en clair dans le fichier, utiliser des secrets ou ajouter le fichier au gitignore

---
kind: pipeline
type: docker
name: continuous-delivery

trigger:
    branch:
        - main
    event:
        - push
# faire une branch par environnement, et trigger sur la branch correspondante

depends_on:
    - continuous-integration
# il depend de lui meme ?

steps:
    - name: build-image
      image: plugins/docker
      environment:
          DATABASE_URL:
              from_secret: database_url_${DRONE_TARGET_BRANCH}
      settings:
          registry: ghcr.io
          repo: ghcr.io/nw-tech/joule-interview-${DRONE_TARGET_BRANCH}
          username:
              from_secret: ghcr_username
          password:
              from_secret: ghcr_password
          dockerfile: Dockerfile
          build_args_from_env:
              - DATABASE_URL

    - name: deploy-image
      image: curlimages/curl:latest
      environment:
          WEBHOOK_URL:
              from_secret: webhook_url_${DRONE_TARGET_BRANCH}
      commands:
          - curl -X POST $WEBHOOK_URL
      depends_on:
          - build-image

    - name: deploy-migration
      image: node # versionning ?
      commands:
          - npx prisma migrate deploy
      environment:
          DATABASE_URL:
              from_secret: database_url_${DRONE_TARGET_BRANCH}
      depends_on:
          - deploy-image
