version: "3.8"
services:
    database:
        image: postgres:13.5
        restart: always # limiter les redémarrages, ne pas boucler : unless-stopped
        environment:
            - POSTGRES_USER=app
            - POSTGRES_PASSWORD=d!@O9p7.4Fg2a # pas de hardcode des passwords
        volumes:
            - database:/var/lib/postgresql/data
        ports:
            - "5432:5432"

    backend:
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            - DATABASE_URL=${DATABASE_URL}
        depends_on:
            - database
        ports:
            - "3000:3000"
# si le backend n'est utilisé que par le docker peut-etre ne pas exposer le port?

volumes:
    database:
# renommer le volume pour quelque chose de plus approprié (que tout ne s'appelle pas database)

# docker recommande aussi d'utiliser des networks pour isoler les services